# Kraken's API public and private keys.
api:
  public_key: "KRAKEN_API_PUBLIC_KEY"
  private_key: "KRAKEN_API_PRIVATE_KEY"

# DCA pairs configuration. You can add as many pairs as you want.
# pair: Name of the pair (list of available pairs: https://api.kraken.com/0/public/AssetPairs)
# delay: Delay in days between each buy limit order.
# amount: Amount of the order in quote asset.
# limit_factor (optional): Create the limit order at a price of current price
#                          multiplied by specified factor (up to 5 digits).
# max_price (optional): Maximum price to create a limit order, after looking at
#                       limit_factor if set (up to 2 digits).
# ignore_differing_orders (optional): May be set to True to ignore any set open or
#                          closed orders within the time delay that differ more than 1%
#                          of the desired amount. This allows to have manually set limit
#                          orders while still DCAing.
# E.g., limit_factor = 0.95 creates a limit order 5% below market price
dca_pairs:
  - pair: "XETHZEUR"
    delay: 1
    amount: 15
    limit_factor: 0.985
    max_price: 2900.10
  - pair: "XXBTZEUR"
    delay: 3
    amount: 20
    ignore_differing_orders: True
